include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    avoid_positional_boolean_parameters: ignore
    comment_references: ignore
    lines_longer_than_80_chars: ignore
    prefer_constructors_over_static_methods: ignore
linter:
  rules:
    public_member_api_docs: false
formatter: 
  page_width: 120
  trailing_commas: preserve

